package status

const (
	OK                         = int64(0)
	ServerSecurityError        = int64(-19001)  // ?
	VersionDifference          = int64(-19002)  // game version not compatible with server
	DecryptionFailure          = int64(-19003)  // error while decrypting param
	ParamHashDifference        = int64(-19004)  // ?
	ServerNextVersion          = int64(-19990)  // ?
	ServerMaintenance          = int64(-19997)  // server is currently undergoing scheduled maintenance
	ServerBusyError            = int64(-19998)  // server is either over capacity or a scheduled operation is taking place
	ServerSystemError          = int64(-19999)  // server code broke
	RequestParamError          = int64(-10100)  // error parsing param?
	NotAvailablePlayer         = int64(-10101)  // ?
	MissingPlayer              = int64(-10102)  // player not found in database
	ExpiredSession             = int64(-10103)  // session expired; should attempt relogin
	InvalidPassword            = int64(-10104)  // login password invalid
	InvalidSerialCode          = int64(-10105)  // invite link not valid
	UsedSerialCode             = int64(-10106)  // invite link already used
	HSPWebAPIError             = int64(-10115)  // problem communicating with HSP API
	ApolloWebAPIError          = int64(-10115)  // problem communicating with Apollo API
	DataMismatch               = int64(-30120)  // ?
	MasterDataMismatch         = int64(-10121)  // ?
	NotEnoughRedRings          = int64(-21030)  // player does not have enough red rings
	NotEnoughRings             = int64(-20131)  // player does not have enough rings
	NotEnoughEnergy            = int64(-20132)  // player does not have enough energy (internal name for challenge/revive tokens)
	RouletteUseLimit           = int64(-30401)  // cannot use the roulette right now (no free spins, tickets, or red rings)
	RouletteBoardReset         = int64(-30411)  // roulette board expired
	CharacterLevelLimit        = int64(-20601)  // character level maxed out already
	AllChaoLevelLimit          = int64(-20602)  // all available chao are already at max level?
	AlreadyInvitedFriend       = int64(-30801)  // friend already invited
	AlreadyRequestedEnergy     = int64(-30901)  // cooldown period still active for requesting energy
	AlreadySentEnergy          = int64(-30902)  // cooldown period still active for sending energy
	ReceiveFailureMessage      = int64(-30910)  // error occurred in GetMessage
	AlreadyExistedPrePurchase  = int64(-11001)  // IAP error
	AlreadyRemovedPrePurchase  = int64(-11002)  // IAP error
	InvalidReceiptData         = int64(-11003)  // IAP error
	AlreadyProcessedReceipt    = int64(-11004)  // IAP error
	EnergyLimitPurchaseTrigger = int64(-21010)  // ? (possibly internal use code?)
	NotStartEvent              = int64(-10201)  // bad event id in request or event has not started yet
	AlreadyEndEvent            = int64(-10202)  // event has ended
	VersionForApplication      = int64(-999002) // ? (This causes the game to connect to the last entry in the server list, according to the code)
	Timeout                    = int64(-7)      // proxy: connection to server timed out
	OtherError                 = int64(-8)      // misc. error not covered by any other code (?)
	NotReachable               = int64(-10)     // proxy: server not reachable
	InvalidResponse            = int64(-20)     // proxy: got bad data from server
	ClientError                = int64(-400)    // proxy: got http 4xx from server
	InternalServerError        = int64(-500)    // proxy: got http 5xx from server
	HSPPurchaseError           = int64(-600)    // HSP: error while processing IAP
	ServerBusy                 = int64(-700)    // proxy: got ServerBusyError from server
)
